### ISSUE TITLE
Stream not available in 2.9.0-beta.1

### ISSUE THREAD

**Issue by jonpitch** [jamesarosen/ember-i18n#400]
ember-i18n `4.2.2` is throwing an error: `Could not find module ember-htmlbars/streams/stream` in Ember `2.9.0-beta.1`. From here:

https://github.com/jamesarosen/ember-i18n/blob/master/addon/stream.js#L15

It appears that `ember-metal/streams/stream` and `ember-htmlbars/streams/stream` are no longer available.

**Comment by jamesarosen** [comment]
Will be resolved by #399

**Comment by jamesarosen** [comment]
Should be fixed in [v4.3.0](https://github.com/jamesarosen/ember-i18n/releases/tag/v4.3.0)

**Comment by jonpitch** [comment]
Thanks for the fast turnaround on v4.3.0 but unfortunately I still receive `Could not find module ember-metal/streams/stream`. Let me know how I can help troubleshoot.

**Comment by jamesarosen** [comment]
#401 might be the issue
